version: "3.8"

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - FLASK_REDIS_URL=redis://redis:6379/0
      - FLASK_OPENCAGE_KEY=${FLASK_OPENCAGE_KEY}
    depends_on:
      - redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
